### ISSUE TITLE
Add support for authorization credentials

### ISSUE THREAD

**Issue by koep** [nalbury/promql-cli#14]
Hi @nalbury ,

First of all, thank you for this tool! It is super useful.

The Prometheus common library meanwhile supports the usage of authorization credentials (for example bearer tokens) - https://github.com/prometheus/common/pull/272. It would be extremely useful to be able to use those with `promql-cli`.

If you don't think so, feel free to close this issue!

Christian

**Comment by nalbury** [comment]
No that's a great idea, should be simple enough to configure the client. 

Curious what you'd want the UI/UX to look like? I'm inclined to stick to something like environment variables for that vs allowing them to be passed via cmd line flags or the config file?

**Comment by koep** [comment]
I personally don't have a preference for this. For context, I've been making a few super [ugly changes](https://github.com/koep/promql-cli/commit/5cb54ce8862c237ec3a6fdadf2c2e12e11a6ab6e#diff-70928c3767b9252b308678af7ee7d3495e4b1634e288ad05f00159dd21dc16d4) to make a quick PoC work in my OpenShift environment. If I could achieve the same thing with cmd line flags (e. g. here is your auth token) that would be more than enough!

**Comment by nalbury** [comment]
Look out for a new release soon which, amongst a few other things, will include this.

**Comment by nalbury** [comment]
@koep this is merged into the latest `main` branch if you want to try it out, otherwise it will be included in the next release for sure.

The [README](https://github.com/nalbury/promql-cli#http-auth) has been updated to reflect the authorization options.

If it helps, I've also added prebuilt container images for promql-cli which may make testing a version different than what you have installed a little easier:

```
docker pull ghcr.io/nalbury/promql-cli:main
```

Going to close this for now, but feel free to reopen if it doesn't work as advertised.
